version: "3.9"

services:
  db:
    image: postgres:13-alpine
    ports:
      - "5559:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - ./schema/postgresql:/docker-entrypoint-initdb.d

  aws:
    image: localstack/localstack:3.0
    ports:
      - "4569:4566"
    environment:
      - SERVICES=sns,sqs
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=ap-northeast-2
    volumes:
      - ./schema/localstack/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh
      - /var/run/docker.sock:/var/run/docker.sock

  elasticsearch:
    build:
      context: ./schema/elasitcsearch
      dockerfile: Dockerfile
    ports:
      - "9222:9200"
      - "9333:9300"
    environment:
      - ELASTIC_USERNAME=test
      - ELASTIC_PASSWORD=test
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - discovery.type=single-node